[local]
localhost

[mongodb]
mongodb.devopskiran.online
[redis]
redis.devopskiran.online
[mysql]
mysql.devopskiran.online
[rabbitmq]
rabbitmq.devopskiran.online
[catalogue]
catalogue.devopskiran.online
[cart]
cart.devopskiran.online
[frontend]
frontend.devopskiran.online