- name: roboshop instance management
  hosts: local
  connection: local
  # for connecting to AWS ansible run the python code in background so we need to execute this command pip3.9 install boto3 botocore
  vars:
    instances: ["mongodb","redis","mysql","rabbitmq","frontend","cart"]
    image_id: ami-0220d79f3f480ecf5
    domain_name: devopskiran.online
    action: create
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      #state: present
      instance_type: t3.micro
      name: "roboshop-{{ item }}"
      image_id: "{{ image_id }}"
      security_groups: 
      - "roboshop-{{ item }}"
      - roboshop-common
    loop: "{{ instances }}"  
    register: ec2_output
    #when: action == "create"
    when: action == "delete"

  # - name: print output
  #   debug:
  #     msg: "{{ ec2_output }}"

  # - name: create route 53 record
  #   debug:
  #     msg: "Instance name: {{ item.item }} PrivateIp: {{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"
   
  - name: create route 53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" #mangodb.daws.shop
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: action == "create"
    #when: item.item != "frontend"

  - name: create route 53 record for frondend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}" #mangodb.daws.shop
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true # this will overwrite the existing r53 records if present with same name
    loop: "{{ ec2_output.results }}"
    when: 
    - item.item != "frontend"
    - action == "create"
 
  - name: delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}.{{ domain_name }}"
      type: A
      ttl: 1
    loop: "{{ instances }}"  
    when: action == "delete"

  - name: delete r53 records for frontend
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}"
      type: A
      ttl: 1
    loop: "{{ instances }}"  
    when:
    - action == "delete"
    - item == "frontend"